### ISSUE TITLE
ロゴ

### ISSUE THREAD

**Issue by takapi327** [takapi327/Scala-practice#29]
# ポートフォリオロゴ
### HTML
```html
<div id="scene">
  <div id="boxBase">
    <div class="top button"></div>
    <div class="bottom button"></div>
    <div class="front button"></div>
    <div class="back button"></div>
    <div class="left button"></div>
    <div class="right button"></div>
  </div>
</div>
```

CSS
```css
.text {
  display:inline-block;
  position:relative;
  left:50%;
  top:50%;
  transform:translateX(-50%) translateY(-50%);
  font-size:40px;
  color:white;
}
#scene {
  perspective: 1000px;
  width:200px;
  height:200px;
  position:relative;
  top:50vh;
  left:50vw;
  transform:translateX(-50%) translateY(-50%);
}
#boxBase {
  transform-style:preserve-3d;
  width:200px;
  height:200px;
  animation: turnAround 10s linear 0s infinite normal none running;
}
@keyframes turnAround {
  0%{
    transform:rotateX(0deg) rotateY(0deg);
  }
  100%{
    transform:rotateX(360deg) rotateY(360deg);
  }
}
#boxBase > div {
  position:absolute;
  background-color:rgba(100, 100, 100, 0.7);
  border:1px solid black;
  width:198px;
  height:198px;
  cursor: pointer;
}
#boxBase > div:hover {
  background-color:rgba(200, 200, 200, 0.7);
}
#boxBase > div:hover > .text {
  color:black;
  font-weight:bold;
}
#boxBase > .top {
  transform:translateY(100px) rotateX(-90deg);
}
#boxBase > .bottom {
  transform:translateY(-100px) rotateX(90deg);
}
#boxBase > .front {
  transform:translateZ(100px);
}
#boxBase > .back {
  transform:translateZ(-100px) rotateX(180deg);
}
#boxBase > .left {
  transform:translateX(-100px) rotateY(-90deg);
}
#boxBase > .right {
  transform:translateX(100px) rotateY(90deg);
}
```

### JavaScript
```js
const buttons = document.getElementsByClassName("button");

const colors = ["Red", "Blue", "Green", "Yellow", "Pink", "Orange"];
for(let count = 0; count < colors.length; count++){
  buttons[count].innerHTML = '<div class="text">'+ colors[count] + '</div>';
  buttons[count].addEventListener("click", function(){
    document.body.style.backgroundColor = colors[count];
  });
}
```

## 参考文献
[CSS3 立方体](https://qiita.com/AO2324/items/0619a0e9173fda7141a1)
